FROM maven:3.8.4-openjdk-8 AS BUILD_IMAGE

WORKDIR /root

RUN git clone https://github.com/necatisahin/vodafone-garage-automated-ticketing-system && \
    cd vodafone-garage-automated-ticketing-system && \
    mvn clean install

FROM openjdk:8-jre
WORKDIR /app
COPY --from=BUILD_IMAGE /root/vodafone-garage-automated-ticketing-system/target/vodafone-garage-automated-ticketing-system-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java","-jar","vodafone-garage-automated-ticketing-system-0.0.1-SNAPSHOT.jar"]
